export type IconName =
  | 'linkedin'
  | 'github'
  | 'email'
  | 'arrow-down'
  | 'arrow-up-right'
  | 'briefcase'
  | 'graduation'
  | 'calendar'
  | 'menu'
  | 'globe'
  | 'chevron-down'
  | 'webgpu'
  | 'shield'
  | 'cart'
  | 'clock';
